# Show the group hierarchy and hosts
# ansible-inventory -i inventory/hosts.yml --graph

all:
  children:
    windows:
      hosts:
        WinSer1-VM-Dev:
          ansible_host: 20.118.132.207
    linux:
      hosts:
        UbuDoc1-VM-Dev:
          ansible_host: 20.150.139.56